[project]
name = "project-alpha"
version = "0.1.0"
description = "Stock market analysis tools"
authors = [
    {name = "Project Alpha Team",email = "team@example.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "numpy (==1.26.4)",
    "pandas (>=2.3.0,<3.0.0)",
    "pandas-ta (>=0.3.14b0,<0.4.0)",
    "yfinance (>=0.2.63,<0.3.0)",
    "tradingview-ta (>=3.3.0,<4.0.0)",
    "requests (>=2.32.4,<3.0.0)",
    "beautifulsoup4 (>=4.13.4,<5.0.0)",
    "multitasking (>=0.0.11,<0.0.12)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "plotly (>=6.1.2,<7.0.0)",
    "tensorflow (==2.14.0)",
    "tensorflow-probability (==0.22.0)",
    "keras (==2.14.0)",
    "scikit-learn (>=1.7.0,<2.0.0)",
    "joblib (>=1.5.1,<2.0.0)",
    "advanced-ta (==0.1.8)",
    "scipy (>=1.15.3,<2.0.0)",
    "open-webui (>=0.6.15,<0.7.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
